### ISSUE TITLE
Can this plugin be used on Redmine 4.1.1?

### ISSUE THREAD

**Issue by uart-aplex** [fraoustin/redmine_rtmaterial#7]
I want to try the RedmineThemeMaterrial, Does this plugin also must be installed? If it is must, then can I install this plugin into redmine version 4.1.1?

Thanks for share the theme.

**Comment by fraoustin** [comment]
the plugin is not mandatory ... but the plugin give a possibility to manage a color-theme by project
The plugin is ok for Redmine 4.1.1

To test the plugin, you can use Docker.

Sample of Dockerfile

```
FROM redmine:4.1.1

WORKDIR /usr/src/redmine/public/themes
RUN git clone https://github.com/fraoustin/RTMaterial.git
WORKDIR /usr/src/redmine/public/themes/RTMaterial/stylesheets
RUN cp colors/color-red-blue.css colors.css
WORKDIR /usr/src/redmine/plugins
RUN git clone https://github.com/fraoustin/redmine_rtmaterial.git


WORKDIR /usr/src/redmine/
```

to run

```
docker build -t myredmine .
docker run -d -p 3000:3000 -e REDMINE_PLUGINS_MIGRATE=1 --name myredmine myredmine
```

and to connect http://127.0.0.1:3000
