### ISSUE TITLE
ActionView::Template::Error

### ISSUE THREAD

**Issue by gryffcom** [fraoustin/redmine_rtmaterial#8]
I installed the plugin and can't access to project pages: Redmine 500 error. When I try to access to a project page in log file I see:
Started GET "/projects/pebez-ru" for 2001:470:28:934:76d0:2bff:fe7b:5247 at 2020-12-23 17:34:09 +0000
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"pebez-ru"}
  Current user: gryff (id=1)
  Rendering projects/show.html.erb within layouts/base
  Rendered projects/_members_box.html.erb (1.2ms)
  Rendered projects/show.html.erb within layouts/base (22.7ms)
  Rendered plugins/redmine_rtmaterial/app/views/layouts/_view_layouts_base_content.html.erb (53.1ms)
Completed 500 Internal Server Error in 157ms (ActiveRecord: 31.9ms)

ActionView::Template::Error (undefined local variable or method `rtmaterial_color_scheme' for #<Project:0x000000080bdc1a00>
Did you mean?  rtmaterial_current_color_scheme):
    1: <%
    2: color_scheme = @project.nil? ? Setting.plugin_redmine_rtmaterial['default_colors'] : @project.rtmaterial_current_color_scheme
    3: change_icon = @project.nil? ? Setting.plugin_redmine_rtmaterial['change_icon'] : @project.rtmaterial_current_change_icon
    4: %>
    5: <% if !@current_theme.blank? && @current_theme.name.downcase == "rtmaterial" && !color_scheme.blank? %>

plugins/redmine_rtmaterial/lib/redmine_rtmaterial/project_patch.rb:10:in `rtmaterial_current_color_scheme'
plugins/redmine_rtmaterial/app/views/layouts/_view_layouts_base_content.html.erb:2:in `_plugins_redmine_rtmaterial_app_views_layouts__view_layouts_base_content_html_erb__154466434304423352$
lib/redmine/hook/view_listener.rb:61:in `block (2 levels) in render_on'
lib/redmine/hook/view_listener.rb:59:in `map'
lib/redmine/hook/view_listener.rb:59:in `block in render_on'
lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `block in call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:98:in `call_hook'
app/views/layouts/base.html.erb:112:in `_app_views_layouts_base_html_erb__537220462726070165_74160'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

I tried uninstall the plugin - useless. The problem persists. What should I do to resolve the problem?

**Comment by fraoustin** [comment]
Havé you add a parameter coloré material un global settings ?

**Comment by fraoustin** [comment]
Have you add a material color parameter un global setting of redmine ( in plugin manager)

**Comment by gryffcom** [comment]
Default color scheme: amber-grey
but TRMaterial change icon haven't been assigned. I marked this option and made:
rake redmine:plugins:migrate NAME=redmine_rtmaterial --trace
It is the same result as it was before - I can't see project pages.
There are a lot of warning, but all are like: previous definition of RakeFileUtils was here,
except:
Rails Error: Unable to access log file. Please ensure that /usr/local/www/rails/task.gryff.com/log/development.log exists and is writable (ie, make it writable for user and group: chmod 0664 /usr/local/www/rails/task.gryff.com/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed. ** Execute redmine:plugins:migrate
rake aborted!
Mysql2::Error::ConnectionError: Access denied for user 'redmine'@'localhost' to database 'redmine_development'
I have got the config BUNDLE_WITHOUT: "development:test", therefore I didn't configured mysql for it. I don't sure may be it is the reason of the error.
redmine4-4.1.1_3
Bundler       2.1.4
  Platforms   ruby, amd64-freebsd-12
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [amd64-freebsd12]
  Full Path   /usr/local/bin/ruby27
  Config Dir  /usr/local/etc
RubyGems      3.2.2
  Gem Home    /usr/local/lib/ruby/gems/2.7
  Gem Path    /usr/home/gryff/.gem/ruby/2.7:/usr/local/lib/ruby/gems/2.7
  User Home   /home/gryff
  User Path   /home/gryff/.gem/ruby/2.7
  Bin Dir     /usr/local/bin
Tools         
  Git         2.29.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed

**Comment by fraoustin** [comment]
Your error "Mysql2::Error::ConnectionError: Access denied for user 'redmine'@'localhost' to database 'redmine_development'" is bizarre ... 

To test the plugin, i use Docker.

Sample of Dockerfile

```
FROM redmine:4.1.1

WORKDIR /usr/src/redmine/public/themes
RUN git clone https://github.com/fraoustin/RTMaterial.git
WORKDIR /usr/src/redmine/public/themes/RTMaterial/stylesheets
RUN cp colors/color-red-blue.css colors.css
WORKDIR /usr/src/redmine/plugins
RUN git clone https://github.com/fraoustin/redmine_rtmaterial.git

WORKDIR /usr/src/redmine/
```
to run

```
docker build -t myredmine .
docker run -d -p 3000:3000 -e REDMINE_PLUGINS_MIGRATE=1 --name myredmine myredmine
```
and to connect http://127.0.0.1:3000

and all is ok

**Comment by gryffcom** [comment]
I'm sorry I use FreeBSD. As of yet, docker isn’t supported for the FreeBSD operating system, so there’s no way I can use docker on FreeBSD.

**Comment by fraoustin** [comment]
without solution ... a problem with os, i close this issue
